apiVersion: v2
name: istio-core
description: Helm umbrella chart for istio
type: application
version: 1.25.1-bb.1
appVersion: 1.25.1
keywords:
  - istio
  - istiod
  - gateway
icon: https://istio.io/latest/favicons/android-192x192.png
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    This package combines the upstream 
    [`istiod`](https://github.com/istio/istio/tree/master/manifests/charts/istio-control/istio-discovery)
    and 
    [`base`](https://github.com/istio/istio/tree/master/manifests/charts/base) 
    helm charts from the Istio project. All of the Istio components,
    including the helm charts, are released in sync as part of
    the larger Istio project's release cycle.

    You can find the upstream Istio release notes
    [here](https://istio.io/latest/news/releases/).
dependencies:
  - name: base
    version: 1.25.1
    repository: file://chart/charts/base
  - name: istiod
    version: 1.25.1
    repository: file://chart/charts/istiod
