apiVersion: v2
name: istiod
# This version is never actually shipped. istio/release-builder will replace it at build-time
# with the appropriate version
version: 1.23.2
appVersion: 1.23.2
description: Helm chart for istio control plane
keywords:
  - istio
  - istiod
  - istio-discovery
sources:
  - https://github.com/istio/istio
icon: https://istio.io/latest/favicons/android-192x192.png
dependencies:
  - name: base
    version: 1.23.2
    repository: file://../base
  # - name: istiod
  #   version: 1.23.2
  #   repository: file://../istiod
  # - name: gateway
  #   version: 1.23.2
  #   repository: file://chart/charts/gateway

